# data-www
data-www:
    image: busybox
    volumes:
        - ./app:/app

## php-fpm
php-fpm:
    image: php:7-fpm-alpine
    volumes_from:
        - data-www

# nginx
mginx:
    image: nginx:alpine
    volumes_from:
        - data-www
    volumes:
        - ./docker-assets/nginx/vhosts-main.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm
    ports:
        - "8080:80"
#        - "443:443"

# mysql
mysql:
    image: mysql
    volumes:
        - ./docker-assets/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        - ./mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: myproject
        MYSQL_USER: myproject
        MYSQL_PASSWORD: secret
