# data-www
data-www:
    image: busybox
    volumes:
        - ./app:/app

## php-fpm
php-fpm:
    image: php:7-fpm-alpine
    volumes_from:
        - data-www

# nginx
mginx:
    image: nginx:alpine
    volumes_from:
        - data-www
    volumes:
        - ./vhosts-main.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm
    ports:
        - "8080:80"
#        - "443:443"
